#!/usr/bin/env node
/**
 * Flags shelved titles that have no written store line.
 *
 * The 245 curated films in index.html each have a hand-written line in CLERK.
 * The nightly scan shelves several hundred more straight off the services, and
 * those turn over week to week, so they cannot be written in advance and are
 * not worth guessing at. They fall back to the generator, which is correct but
 * plainly worse, and a shelved title can be the top pick.
 *
 * So the job that shelves them also says which ones now need a line. It writes
 * two files, committed alongside the catalog:
 *
 *   data/unwritten.json  the machine list, and the state the next run diffs
 *   data/unwritten.md    a worklist carrying everything needed to write a line
 *
 * The nightly signal is the "arrived recently" section, taken from each entry's
 * firstSeen date, which enrich.mjs sets once and then carries forward. That
 * matters: an earlier version diffed the file against its own previous run,
 * which meant a newly shelved title churned the file twice, once to be flagged
 * and again the next night to be filed. Reading firstSeen instead makes the
 * output a pure function of the catalog and the written lines, so a night when
 * nothing moved rewrites nothing and commits nothing. There is no timestamp in
 * the output for the same reason.
 *
 * The backlog is sorted so the titles most likely to surface come first.
 *
 * Informational: it never fails the build.
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { appendFileSync } from "node:fs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const hm = (m) => {
  const h = Math.floor(m / 60), r = m % 60;
  return h ? h + "h" + (r ? " " + r + "m" : "") : r + "m";
};
const SVC = {NFX:"Netflix", MAX:"Max", HUL:"Hulu", DIS:"Disney+", PRV:"Prime Video",
             APL:"Apple TV+", PAR:"Paramount+", PCK:"Peacock"};

const html = await readFile(join(ROOT, "index.html"), "utf8");

/* the written lines, and the curated catalog they belong to */
const clerkBlock = html.slice(html.indexOf("const CLERK = {"),
                              html.indexOf("\n};", html.indexOf("const CLERK = {")));
const written = new Set([...clerkBlock.matchAll(/^  "((?:[^"\\]|\\.)*)":/gm)].map(m => m[1]));
const rawBlock = html.slice(html.indexOf("const RAW = ["),
                            html.indexOf("\n];", html.indexOf("const RAW = [")));
const curated = new Set([...rawBlock.matchAll(/^\["((?:[^"\\]|\\.)*)",\d{4},/gm)].map(m => m[1]));

let payload;
try {
  payload = JSON.parse(await readFile(join(ROOT, "data/catalog.json"), "utf8"));
} catch {
  console.log("no data/catalog.json yet, nothing shelved to flag");
  process.exit(0);
}
const shelf = Array.isArray(payload.shelf) ? payload.shelf : [];

/* A curated film with no line is a mistake and should be loud. A shelved one
   is expected, and is the worklist. */
const curatedGap = [...curated].filter(t => !written.has(t));

const unwritten = shelf
  .filter(e => e && e.t && !written.has(e.t) && !curated.has(e.t) && e.svcs && e.svcs.length)
  /* most likely to reach a viewer first: fame, then how well it reviewed */
  .sort((a, b) => (b.pop || 0) - (a.pop || 0) || (b.rt || 0) - (a.rt || 0) ||
                  a.t.localeCompare(b.t));

/* Recently arrived, measured against the catalog's own generation date rather
   than the wall clock, so re-running the script on the same data gives the
   same answer. Entries from before firstSeen was tracked carry null and are
   treated as long-standing, which they are. */
const RECENT_DAYS = 7;
const asOf = Date.parse(payload._meta?.generatedAt || "") || Date.now();
const cutoff = asOf - RECENT_DAYS * 864e5;
const isRecent = (e) => {
  const t = e.firstSeen ? Date.parse(e.firstSeen) : NaN;
  return Number.isFinite(t) && t >= cutoff;
};
const fresh = unwritten.filter(isRecent);

const entry = (e) => {
  const svcs = (e.svcs || []).map(c => SVC[c] || c).join(", ");
  const bits = [e.y, hm(e.r || 0), e.mpaa, svcs].filter(Boolean).join(" / ");
  return `### ${e.t}\n` +
         `${bits}\n` +
         `${(e.g || []).join(", ")}${e.d && e.d !== "Unknown" ? " / dir. " + e.d : ""}\n` +
         (e.h ? `> ${e.h}\n` : "");
};

const md =
`# Shelved titles with no store line

Written lines live in \`CLERK\` in index.html. Every one of the ${curated.size} curated
films has one. The titles below arrived from the nightly scan instead, so they
fall back to the generated copy until somebody writes them.

Sorted with the ones most likely to be recommended first. Regenerated by
\`scripts/unwritten.mjs\` on every scan, so edits here are overwritten: write the
line into \`CLERK\` and the title leaves this file on the next run.

Shelved: ${shelf.length}. Unwritten: ${unwritten.length}. Arrived in the last ${RECENT_DAYS} days: ${fresh.length}.

## Arrived in the last ${RECENT_DAYS} days

${fresh.length ? fresh.map(entry).join("\n") : "Nothing recent.\n"}
## Backlog

${unwritten.filter(e => !isRecent(e)).map(entry).join("\n")}`;

await writeFile(join(ROOT, "data/unwritten.md"), md);
/* No timestamp on purpose: this file must be identical when nothing moved. */
await writeFile(join(ROOT, "data/unwritten.json"), JSON.stringify({
  shelved: shelf.length,
  unwritten: unwritten.length,
  recent: fresh.map(e => e.t),
  titles: unwritten.map(e => e.t)
}, null, 1) + "\n");

const lines = [];
if (curatedGap.length) {
  lines.push(`**${curatedGap.length} curated film(s) have no written line**, which should not happen:`);
  curatedGap.slice(0, 20).forEach(t => lines.push(`- ${t}`));
  lines.push("");
}
lines.push(`Shelved titles: ${shelf.length}. Without a store line: ${unwritten.length}.`);
if (fresh.length) {
  lines.push("", `Arrived in the last ${RECENT_DAYS} days (${fresh.length}), most likely to surface first:`);
  fresh.slice(0, 25).forEach(e => lines.push(`- ${e.t} (${e.y}, ${hm(e.r || 0)})`));
  if (fresh.length > 25) lines.push(`- and ${fresh.length - 25} more, listed in data/unwritten.md`);
} else {
  lines.push("", `Nothing shelved in the last ${RECENT_DAYS} days needs a line.`);
}
const report = lines.join("\n");
console.log(report);

if (process.env.GITHUB_STEP_SUMMARY) {
  appendFileSync(process.env.GITHUB_STEP_SUMMARY, "## Store lines\n\n" + report + "\n");
}
if (process.env.GITHUB_OUTPUT) {
  appendFileSync(process.env.GITHUB_OUTPUT, `new_count=${fresh.length}\nunwritten=${unwritten.length}\n`);
}
